---
# tasks file for nodejs
- name: Add NodeJS deb source
  shell: "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -"

- name: Install NodeJS
  become: true
  apt:
    name=nodejs
    state=present

