---
# defaults file for golang

go_version: '1.14.13'

go_tarball: 'go{{ go_version }}.linux-amd64.tar.gz'

go_tarball_url: "https://dl.google.com/go/{{ go_tarball }}"

go_tarball_checksum: 'sha256:bfea0c8d7b70c1ad99b0266b321608db57df75820e8f4333efa448a43da01992'

go_install_dir: '/usr/local/'