---
# tasks file for common
- name: Apt Update
  become: true
  apt: update_cache=yes

- name: Install libraries with apt
  become: true
  apt: name={{ item }} state=present
  with_items:
    - wget
    - vim
    - git
    - curl
    - tmux
    - apt-transport-https
    - ca-certificates
    - software-properties-common
