---
# tasks file for common
- name: Apt Update
  sudo: yes
  apt: update_cache=yes

- name: Install libraries with apt
  apt: name={{ item }} state=present
  with_items:
    - wget
    - vim
    - git
    - curl
    - tmux
