---
# tasks file for docker
- name: Add Docker offical GPG key
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

- name: Add docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name:  Install docker-ce
  become: true
  apt: name={{ item }} state=present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Post Install Docker
  become: true
  shell: groupadd docker && usermod -aG docker {{ ansible_user_id }}
  ignore_errors: True

- name: Install docker compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755