---
# tasks file for php
- name: Install PHP 7.0
  become: true
  apt: name={{ item }} state=present
  with_items:
    - php7.0
    - php7.0-cli
    - php7.0-fpm
    - php7.0-mysql
    - php7.0-curl
    - php7.0-gd
    - php7.0-ldap
    - php7.0-mbstring
    - php7.0-snmp
    - php7.0-xml
    - php7.0-zip
    - php7.0-sqlite3
    - php7.0-mcrypt
    - php7.0-opcache
    - php7.0-cgi

